### PR TITLE
💧 Remove memory leak in TimerJS + other small fixes

### LINKED ISSUE #307: Memory leak on the TimerJS implementation
The TimerJS implementation in the STL has a memory leak, the array keeps being increased. We should perhaps use a circular buffer or a Map instead.

### PR DESCRIPTION
**Pull request by fungiboletus**
We now use `Map` because we are modern people writing modern JavaScript.

Fix #307

### CODE REVIEW

**Review by brice-morin — APPROVED** [review]

**Comment by brice-morin** [comment]
The driftless JS timer has not been updated... Not sure if it ever worked (and we probably need to update the version of driftless too...). We could alternatively remove it if you are not going to use it?

File: compilers/javascript/src/main/java/org/thingml/compilers/javascript/JSCompiler.java [hunk 1]
```diff
@@ -1,153 +1,153 @@
...
+			events.append("  function " + className + "(from, port,...params) {\n");
+			events.append("    this.type = '" + type + "';\n");
+			events.append("    this.port = port;\n");
+			events.append("    this.from = from;\n");
+			StringBuilder params = new StringBuilder();
+			for(Parameter p : m.getParameters()) {
+				events.append("    this." + p.getName() + " = params[" + m.getParameters().indexOf(p) + "];\n");
+				if (m.getParameters().indexOf(p) > 0)
+					params.append(" + ', ' + ");
+				params.append('this.' + p.getName());
```
Comment (brice-morin) [inline compilers/javascript/src/main/java/org/thingml/compilers/javascript/JSCompiler.java:88]: @fungiboletus that should fix the bug you found in the toString (see line 95 below)

File: language/thingml/src/org/thingml/xtext/validation/checks/FunctionUsage.xtend [hunk 2]
```diff
@@ -1,281 +1,281 @@
...
+	def checkUsage(Function f) {
+		val thing = ThingMLHelpers.findContainingThing(f)
+		//Checks if the containing thing calls the function
+		if (ActionHelper.getAllActions(thing, FunctionCallStatement).exists[call | call.function == f || call.function.name == f.name])
+			return;
+		if (ThingMLHelpers.getAllExpressions(thing, FunctionCallExpression).exists[call | call.function == f || call.function.name == f.name])
+			return;			
+		
+		//if not, check if any thing that includes the function actually calls it
+		val isUsedByIncludingThings = ThingHelper.allIncludingThings(thing)
```
Comment (brice-morin) [inline language/thingml/src/org/thingml/xtext/validation/checks/FunctionUsage.xtend:54]: that should fix #306 as we now check including things (things that import the function directly or not), rather than included thing (which had no chance to import the function).

**Comment by fungiboletus** [comment]
> The driftless JS timer has not been updated... Not sure if it ever worked (and we probably need to update the version of driftless too...). We could alternatively remove it if you are not going to use it?

The drift less library has received no updates. I think we can keep it for now, we may want to use it in the future.
